# Pytroch 损失函数 NLLLoss & CrossEntropyLoss详解

# 1. NLLLoss

In [5]:
import torch
import torch.nn as nn

In [4]:
# 假设输入m个样本，分成F类， 所以最后一个隐藏层含有F个特征，这里m=4, F =3, 举个例子：
input1 = torch.randn(4, 3)
input1

tensor([[-0.8233, -1.2627, -0.2428],
        [-1.2468,  0.0922,  0.6837],
        [-1.2785, -0.7575, -0.5185],
        [ 0.4479,  0.2094, -1.6592]])

In [6]:
# 对每个隐藏层输出做softmax, 可以得到每个样本的概率分布
# 这里的dim=1，表示沿着列的方向计算Softmax, 可以看到输出的每一行的和都为1
sm = nn.Softmax(dim=1)
sm_out = sm(input1)
sm_out

tensor([[0.2914, 0.1878, 0.5208],
        [0.0854, 0.3259, 0.5887],
        [0.2074, 0.3492, 0.4434],
        [0.5237, 0.4126, 0.0637]])

In [7]:
# 然后对Softmax的结果去自然对数, Softmax后的数值都在0~1之间，所以ln之后值域是负无穷到0
sm_out = torch.log(sm_out)
sm_out

tensor([[-1.2329, -1.6724, -0.6525],
        [-2.4603, -1.1213, -0.5298],
        [-1.5731, -1.0522, -0.8132],
        [-0.6468, -0.8853, -2.7539]])

In [8]:
# 现在假设我们的label=[2,0,1,0]
# 根据标签, 我们取sm_out[0][2], sm_out[1][0], sm_out[2][1], sm_out[3][0], 将他们去掉负号， 再求均值。
# 其实就是对每个样本的交叉熵求均值
out = (0.6525 + 2.4603 + 1.0522 + 0.6468) / 4
out

1.20295

In [9]:
# 上面的公式就是NLLLoss损失函数
# loss合理性： 如果正确标签对应的那一列的softmax值大的话，那么取了自然对数再取反之后就比较小，那么loss就小。也就是说预测正确的话，loss小
#            如果正确标签对应的那一列的softmax值小的话，那么取了自然对数再取反之后就比较大，那么loss就大。也就是说预测错误的话，loss大

# 下面使用NLLLoss函数验证一下：
loss = nn.NLLLoss()
target = torch.tensor([2, 0 ,1, 0])
loss(sm_out, target)

tensor(1.2029)

# 2. CrossEntropyLoss

In [10]:
# CrossEntropyLoss就是把以上Softmax–Log–NLLLoss合并成一步，我们用刚刚随机出来的input直接验证一下
loss2 = nn.CrossEntropyLoss()
loss2(input1, target)

tensor(1.2029)